parameters:
    social_post.facebook.provider: MartinGeorgiev\SocialPost\Provider\Facebook\SDK5
    social_post.twitter.provider: MartinGeorgiev\SocialPost\Provider\Twitter\TwitterOAuth07
    social_post.all_in_one: MartinGeorgiev\SocialPost\Provider\AllInOne

services:
    facebook:
        class: Facebook\Facebook
        arguments:
            - "%social_post.configuration.facebook%"
        public: false
        
    twitter:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments:
            - "%social_post.configuration.twitter.consumer_key%"
            - "%social_post.configuration.twitter.consumer_secret%"
            - "%social_post.configuration.twitter.access_token%"
            - "%social_post.configuration.twitter.access_token_secret%"
        public: false
    
    social_post.facebook:
        class: "%social_post.facebook.provider%"
        arguments:
            - "@facebook"
            - "%social_post.configuration.facebook.page_id%"
        public: false
    
    social_post.twitter:
        class: "%social_post.twitter.provider%"
        arguments:
            - "@twitter"
        public: false
        
    social_post:
        class: "%social_post.all_in_one%"