parameters:
    social_post.linkedin.provider: MartinGeorgiev\SocialPost\Provider\LinkedIn\HappyrLinkedInApiClient

services:
    linkedin:
        class: Happyr\LinkedIn\LinkedIn
        arguments:
            - "%social_post.configuration.linkedin.client_id%"
            - "%social_post.configuration.linkedin.client_secret%"
        public: false
        
    social_post.linkedin:
        class: "%social_post.linkedin.provider%"
        arguments:
            - "@linkedin"
            - "%social_post.configuration.linkedin.access_token%"
            - "%social_post.configuration.linkedin.company_page_id%"
        public: false