parameters:
    social_post.twitter.provider: MartinGeorgiev\SocialPost\Provider\Twitter\TwitterOAuth07

services:
    twitter:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments:
            - "%social_post.configuration.twitter.consumer_key%"
            - "%social_post.configuration.twitter.consumer_secret%"
            - "%social_post.configuration.twitter.access_token%"
            - "%social_post.configuration.twitter.access_token_secret%"
        public: false
        
    social_post.twitter:
        class: "%social_post.twitter.provider%"
        arguments:
            - "@twitter"
        public: false